### PR TITLE
Change the preprocess

### PR DESCRIPTION
**Pull request by ThomasDupin**
Adding the else for the df meta, and the changement to the merge function to work with 1 or 3 csv file

### CODE REVIEW

**Comment by bastianilso** [comment]
Hey Thomas, few things:
 * take a look at the "files changed" tab. You will see that you are submitting changes to both preprocess.R and loadrawdata.R but we only need changes to loadrawdata.R in this commit.
 * R studio does not do a very good job of visualising what lines have changed. This means that your commit contains many smaller style changes (unnecessary line additions, small unnecessary changes) that needs cleaning up. I suggest you reset your commit and use something like Visual Studio Code which will visualize with green/red what you have changed, so its easy to clean. Alternatively, start from a clean version of the script and copy-paste your changes into it, only changing what is necessary.

**Review by bastianilso — CHANGES_REQUESTED** [review]
🐇

**Comment by ThomasDupin** [comment]
Okay i made the change normally,  reverted my commit as you said

**Comment by ThomasDupin** [comment]
Okay the new pull request is here

**Comment by bastianilso** [comment]
Code looks good, and, assuming the code we are merging will work for the Arduino logging case too, then I think this is ready to go in. Thanks for the cleanup Thomas!

**Review by bastianilso — APPROVED** [review]
lgtm

**Pull request merged**
